import { Forecast, NextForecastList } from "@/resources/weather/types";

export const mockForecastResponse: Forecast = {
  location: {
    name: "New York",
    region: "New York",
    country: "United States",
    lat: 40.7128,
    lon: -74.006,
    tz_id: "America/New_York",
    localtime_epoch: 1634104800,
    localtime: "2024-10-29 14:00",
  },
  current: {
    last_updated_epoch: 1634104800,
    last_updated: "2024-10-29 13:45",
    temp_c: 22.3,
    temp_f: 72.1,
    is_day: 1,
    condition: {
      text: "Partly Cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 10.4,
    wind_kph: 16.7,
    wind_degree: 240,
    wind_dir: "WSW",
    pressure_mb: 1015.0,
    pressure_in: 29.97,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 60,
    cloud: 50,
    feelslike_c: 22.3,
    feelslike_f: 72.1,
    windchill_c: 22.3,
    windchill_f: 72.1,
    heatindex_c: 24.0,
    heatindex_f: 75.2,
    dewpoint_c: 14.5,
    dewpoint_f: 58.1,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 5.0,
    gust_mph: 15.6,
    gust_kph: 25.0,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-10-29",
        date_epoch: 1634104800,
        day: {
          maxtemp_c: 25.0,
          maxtemp_f: 77.0,
          mintemp_c: 18.0,
          mintemp_f: 64.4,
          avgtemp_c: 21.5,
          avgtemp_f: 70.7,
          maxwind_mph: 15.5,
          maxwind_kph: 25.0,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 65,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 7.0,
          totalsnow_cm: 0,
        },
        astro: {
          sunrise: "07:15 AM",
          sunset: "06:30 PM",
          moonrise: "04:00 PM",
          moonset: "03:00 AM",
          moon_phase: "Waxing Crescent",
          moon_illumination: 25,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1634104800,
            time: "2024-10-29 00:00",
            temp_c: 18.0,
            temp_f: 64.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 220,
            wind_dir: "SW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 20,
            feelslike_c: 18.0,
            feelslike_f: 64.4,
            windchill_c: 18.0,
            windchill_f: 64.4,
            heatindex_c: 18.0,
            heatindex_f: 64.4,
            dewpoint_c: 12.0,
            dewpoint_f: 53.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 1.0,
            snow_cm: 0,
          },
        ],
      },
    ],
  },
};

export const mockNextForecastResponse: NextForecastList = {
  averageHumidity: 65,
  averageTemperature: 21,
  forecastDate: "2024-10-29",
  forecastIcon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
  forecastLocationName: "New York",
  hourlyForecast: [
    {
      chance_of_rain: 0,
      chance_of_snow: 0,
      cloud: 20,
      condition: {
        code: 1000,
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        text: "Clear",
      },
      dewpoint_c: 12,
      dewpoint_f: 53.6,
      feelslike_c: 18,
      feelslike_f: 64.4,
      gust_kph: 19.8,
      gust_mph: 12.3,
      heatindex_c: 18,
      heatindex_f: 64.4,
      humidity: 70,
      is_day: 0,
      precip_in: 0,
      precip_mm: 0,
      pressure_in: 29.97,
      pressure_mb: 1015,
      snow_cm: 0,
      temp_c: 18,
      temp_f: 64.4,
      time: "2024-10-29 00:00",
      time_epoch: 1634104800,
      uv: 1,
      vis_km: 10,
      vis_miles: 6,
      will_it_rain: 0,
      will_it_snow: 0,
      wind_degree: 220,
      wind_dir: "SW",
      wind_kph: 14,
      wind_mph: 8.7,
      windchill_c: 18,
      windchill_f: 64.4,
    },
  ],
};
